"use client";

import { useEffect, useState } from "react";
import type { Locale } from "./i18n";
import { researchosApi, type DataConnector } from "../lib/api-client";

const copy = {
  "zh-CN": { title:"数据连接器", intro:"连接行情、宏观、基本面与另类数据来源。密钥只在服务端加密保存。", save:"保存并启用", test:"测试连接", run:"运行样例", remove:"移除密钥", docs:"官方文档", keyless:"无需密钥", bridge:"需要桥接服务", licensed:"需要机构授权", configured:"已配置", available:"可连接", security:"API Key 会在服务端加密，永不返回浏览器，也不会写入 Git。", rows:"条记录" },
  "zh-TW": { title:"資料連接器", intro:"連接行情、宏觀、基本面與另類資料來源。密鑰只在伺服器端加密保存。", save:"保存並啟用", test:"測試連接", run:"執行樣例", remove:"移除密鑰", docs:"官方文件", keyless:"無需密鑰", bridge:"需要橋接服務", licensed:"需要機構授權", configured:"已設定", available:"可連接", security:"API Key 會在伺服器端加密，永不返回瀏覽器，也不會寫入 Git。", rows:"條記錄" },
  en: { title:"Data connectors", intro:"Connect market, macro, fundamentals, and alternative-data providers. Secrets stay encrypted on the server.", save:"Save & enable", test:"Test connection", run:"Run sample", remove:"Remove key", docs:"Documentation", keyless:"No key required", bridge:"Bridge required", licensed:"License required", configured:"Configured", available:"Available", security:"API keys are encrypted at rest, never returned to the browser, and never written to Git.", rows:"records" },
};

export default function DataConnectorSettings({ locale, active }: { locale: Locale; active: boolean }) {
  const words=copy[locale]; const [connectors,setConnectors]=useState<DataConnector[]>([]); const [selectedId,setSelectedId]=useState<string>(); const [apiKey,setApiKey]=useState(""); const [busy,setBusy]=useState<string>(); const [message,setMessage]=useState<string>(); const [sample,setSample]=useState<{dataset:string;latencyMs:number;count:number}>();
  const refresh=async()=>{const result=await researchosApi.listConnectors();setConnectors(result.connectors);setSelectedId(id=>id??result.connectors[0]?.id)};
  useEffect(()=>{if(!active)return;let cancelled=false;void researchosApi.listConnectors().then(result=>{if(!cancelled){setConnectors(result.connectors);setSelectedId(id=>id??result.connectors[0]?.id)}}).catch(error=>{if(!cancelled)setMessage(error instanceof Error?error.message:"Connector catalog unavailable")});return()=>{cancelled=true}},[active]);
  const selected=connectors.find(item=>item.id===selectedId); const query=selected?.id==="fred"?{series_id:"GDP",limit:5}:selected?.id==="tushare"?{api_name:"trade_cal",exchange:"SSE"}:selected?.id==="alpha-vantage"?{function:"TIME_SERIES_DAILY",symbol:"IBM"}:selected?.id==="nasdaq-data-link"?{dataset:"FRED/GDP",limit:5}:selected?.id==="world-bank"?{country:"US",indicator:"NY.GDP.MKTP.CD"}:selected?.id==="yahoo-finance"?{symbol:"NVDA",range:"1mo"}:{};
  const act=async(action:"save"|"test"|"query"|"remove")=>{if(!selected)return;setBusy(action);setMessage(undefined);setSample(undefined);try{if(action==="save")await researchosApi.configureConnector(selected.id,apiKey,true);if(action==="test"){const r=await researchosApi.testConnector(selected.id);setMessage(`${words.configured} · ${r.latencyMs} ms`)}if(action==="query"){const r=await researchosApi.queryConnector(selected.id,query);setSample({dataset:r.dataset,latencyMs:r.latencyMs,count:Array.isArray(r.rows)?r.rows.length:Object.keys(r.rows??{}).length})}if(action==="remove")await researchosApi.clearConnector(selected.id);setApiKey("");await refresh()}catch(error){setMessage(error instanceof Error?error.message:"Connector operation failed")}finally{setBusy(undefined)}};
  return <><div className="settings-head"><span>FINANCIAL DATA LAYER</span><h2>{words.title}</h2><p>{words.intro}</p></div><div className="connector-security"><i>⌁</i><span><b>Server-side secret policy</b><small>{words.security}</small></span></div><div className="connector-console"><div className="connector-list">{connectors.map(item=><button key={item.id} className={selectedId===item.id?"active":""} onClick={()=>{setSelectedId(item.id);setApiKey("");setMessage(undefined);setSample(undefined)}}><i>{item.mark}</i><span><b>{item.name}</b><small>{item.category} · {item.institution}</small></span><em className={item.configured?"connected":""}>{item.configured?"●":"○"}</em></button>)}</div><div className="connector-detail">{selected&&<><div className="connector-detail-head"><span className="extension-mark">{selected.mark}</span><span><h3>{selected.name}</h3><small>{selected.coverage}</small></span><b>{selected.configured?words.configured:selected.runtime==="native"?words.available:selected.runtime==="licensed"?words.licensed:words.bridge}</b></div>{selected.legalNote&&<p className="connector-legal">{selected.legalNote}</p>}{selected.runtime==="native"?<>{selected.keyRequired?<label className="connector-key"><span>API Key</span><input type="password" autoComplete="off" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder={selected.configured?"••••••••":selected.keyPlaceholder}/></label>:<div className="connector-keyless">✓ {words.keyless}</div>}<div className="connector-actions"><button className="button primary" disabled={!!busy||(selected.keyRequired&&!selected.configured&&!apiKey.trim())} onClick={()=>void act("save")}>{words.save}</button><button className="button" disabled={!!busy||!selected.configured} onClick={()=>void act("test")}>{words.test}</button><button className="button" disabled={!!busy||!selected.configured} onClick={()=>void act("query")}>{words.run}</button></div>{selected.configured&&selected.keyRequired&&<button className="connector-remove" onClick={()=>void act("remove")}>{words.remove}</button>}</>:<p className="connector-unavailable">{selected.runtime==="licensed"?words.licensed:words.bridge}</p>}<a className="connector-docs" href={selected.docsUrl} target="_blank" rel="noreferrer">{words.docs} ↗</a>{message&&<p className="connector-message">{message}</p>}{sample&&<div className="connector-sample"><span>SAMPLE RESULT</span><b>{sample.dataset}</b><small>{sample.count} {words.rows} · {sample.latencyMs} ms</small></div>}</>}</div></div></>;
}
