"""initial deterministic asset foundation

Revision ID: 25298139920f
Revises:
Create Date: 2026-08-05 12:13:29.676044
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "25298139920f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blobs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("storage_mode", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(op.f("ix_blobs_sha256"), "blobs", ["sha256"], unique=True)
    op.create_table(
        "workspaces",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("logical_name", sa.String(length=512), nullable=False),
        sa.Column("source_key", sa.String(length=512), nullable=True),
        sa.Column("current_version_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "source_key", name="uq_asset_workspace_source"),
    )
    op.create_index(
        op.f("ix_assets_current_version_id"), "assets", ["current_version_id"], unique=False
    )
    op.create_index(op.f("ix_assets_workspace_id"), "assets", ["workspace_id"], unique=False)
    op.create_index(
        "ix_assets_workspace_name", "assets", ["workspace_id", "logical_name"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("subject_type", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.String(length=64), nullable=False),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_workspace_id"), "audit_events", ["workspace_id"], unique=False
    )
    op.create_index(
        "ix_audit_workspace_created", "audit_events", ["workspace_id", "created_at"], unique=False
    )
    op.create_table(
        "ingest_batches",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("uploaded_by", sa.String(length=128), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("auto_summary", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingest_batches_workspace_id"), "ingest_batches", ["workspace_id"], unique=False
    )
    op.create_table(
        "asset_versions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("asset_id", sa.String(length=64), nullable=False),
        sa.Column("parent_version_id", sa.String(length=64), nullable=True),
        sa.Column("blob_id", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("format_kind", sa.String(length=32), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("source_filename", sa.String(length=1024), nullable=False),
        sa.Column("deterministic_metadata", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["blob_id"],
            ["blobs.id"],
        ),
        sa.ForeignKeyConstraint(["parent_version_id"], ["asset_versions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "content_hash", name="uq_asset_version_content"),
    )
    op.create_index(
        op.f("ix_asset_versions_asset_id"), "asset_versions", ["asset_id"], unique=False
    )
    op.create_index(op.f("ix_asset_versions_blob_id"), "asset_versions", ["blob_id"], unique=False)
    op.create_index(
        op.f("ix_asset_versions_content_hash"), "asset_versions", ["content_hash"], unique=False
    )
    op.create_table(
        "ingest_items",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("batch_id", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.String(length=1024), nullable=False),
        sa.Column("source_key", sa.String(length=512), nullable=True),
        sa.Column("detected_mime", sa.String(length=255), nullable=True),
        sa.Column("format_kind", sa.String(length=32), nullable=True),
        sa.Column("blob_id", sa.String(length=64), nullable=True),
        sa.Column("resolved_asset_id", sa.String(length=64), nullable=True),
        sa.Column("created_version_id", sa.String(length=64), nullable=True),
        sa.Column("resolution_status", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("warnings_json", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["batch_id"], ["ingest_batches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["blob_id"],
            ["blobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_version_id"],
            ["asset_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingest_items_batch_id"), "ingest_items", ["batch_id"], unique=False)
    op.create_table(
        "representations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("representation_type", sa.String(length=32), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("blob_id", sa.String(length=64), nullable=False),
        sa.Column("generator", sa.String(length=128), nullable=False),
        sa.Column("generator_version", sa.String(length=64), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["blob_id"],
            ["blobs.id"],
        ),
        sa.ForeignKeyConstraint(["version_id"], ["asset_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "version_id",
            "representation_type",
            "generator",
            "generator_version",
            name="uq_representation_generator",
        ),
    )
    op.create_index(
        op.f("ix_representations_blob_id"), "representations", ["blob_id"], unique=False
    )
    op.create_index(
        op.f("ix_representations_version_id"), "representations", ["version_id"], unique=False
    )
    op.create_table(
        "fragments",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("representation_id", sa.String(length=64), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("fragment_type", sa.String(length=32), nullable=False),
        sa.Column("locator_json", sa.JSON(), nullable=False),
        sa.Column("text_or_value", sa.Text(), nullable=True),
        sa.Column("excerpt_hash", sa.String(length=64), nullable=False),
        sa.Column("quality", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["representation_id"], ["representations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["version_id"], ["asset_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("representation_id", "ordinal", name="uq_fragment_ordinal"),
    )
    op.create_index(op.f("ix_fragments_excerpt_hash"), "fragments", ["excerpt_hash"], unique=False)
    op.create_index(
        op.f("ix_fragments_representation_id"), "fragments", ["representation_id"], unique=False
    )
    op.create_index(op.f("ix_fragments_version_id"), "fragments", ["version_id"], unique=False)
    op.create_index(
        "ix_fragments_version_representation",
        "fragments",
        ["version_id", "representation_id"],
        unique=False,
    )
    op.create_table(
        "parse_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("parser_name", sa.String(length=128), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("representation_id", sa.String(length=64), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["representation_id"],
            ["representations.id"],
        ),
        sa.ForeignKeyConstraint(["version_id"], ["asset_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_id", "parser_name", "parser_version", name="uq_parse_run"),
    )
    op.create_index(op.f("ix_parse_runs_version_id"), "parse_runs", ["version_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parse_runs_version_id"), table_name="parse_runs")
    op.drop_table("parse_runs")
    op.drop_index("ix_fragments_version_representation", table_name="fragments")
    op.drop_index(op.f("ix_fragments_version_id"), table_name="fragments")
    op.drop_index(op.f("ix_fragments_representation_id"), table_name="fragments")
    op.drop_index(op.f("ix_fragments_excerpt_hash"), table_name="fragments")
    op.drop_table("fragments")
    op.drop_index(op.f("ix_representations_version_id"), table_name="representations")
    op.drop_index(op.f("ix_representations_blob_id"), table_name="representations")
    op.drop_table("representations")
    op.drop_index(op.f("ix_ingest_items_batch_id"), table_name="ingest_items")
    op.drop_table("ingest_items")
    op.drop_index(op.f("ix_asset_versions_content_hash"), table_name="asset_versions")
    op.drop_index(op.f("ix_asset_versions_blob_id"), table_name="asset_versions")
    op.drop_index(op.f("ix_asset_versions_asset_id"), table_name="asset_versions")
    op.drop_table("asset_versions")
    op.drop_index(op.f("ix_ingest_batches_workspace_id"), table_name="ingest_batches")
    op.drop_table("ingest_batches")
    op.drop_index("ix_audit_workspace_created", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_workspace_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_assets_workspace_name", table_name="assets")
    op.drop_index(op.f("ix_assets_workspace_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_current_version_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_table("workspaces")
    op.drop_index(op.f("ix_blobs_sha256"), table_name="blobs")
    op.drop_table("blobs")
    # ### end Alembic commands ###
